Issue85 back
matsuoharuki/pbl2_group2 pull request #107
Opened 2020-12-21 07:16 UTC by ONourry

For #85 Added getUserById function which allows us to find and return a user in the database using the userId

## successful query
http://localhost:5000/user/getUserById/b2df6835-bce6-4619-9896-643dcfb9645f

2020-12-21T07:13:35.905Z [UserSQL] info: Fetching user with id: b2df6835-bce6-4619-9896-643dcfb9645f
2020-12-21T07:13:35.916Z [userController] debug: Successfully fetched user: b2df6835-bce6-4619-9896-643dcfb9645f

returned value in postman shows the user's data
```
## bad query
http://localhost:5000/user/getUserById/b2df6835-bce6-4619-9896-643dcfb9645f6

2020-12-21T07:14:50.849Z [userController] info: Could not fetched user with id b2df6835-bce6-4619-9896-643dcfb9645f6: {"success":false,"data":"User does not exist"}

returned value: 
{
    "success": false,
    "error": "User does not exist"
}

2020-12-21 07:51 UTC, kyamatek requested changes

2020-12-21 07:51 UTC, kyamatek commented on back/src/route/userController.js
> +const UserSQL = require('../database/UserSQL');
there are two userSQL

2020-12-21 09:05 UTC, ShimizuKazuki reviewed
```
pbl2-back | Example app listening on port:5000
pbl2-back | (node:16) UnhandledPromiseRejectionWarning: ReferenceError: UserSQL is not defined
pbl2-back |     at getUserById (/app/src/route/userController.js:101:9)
```
Something wrong...

2020-12-21 09:14 UTC, ONourry commented
> ```
> pbl2-back | Example app listening on port:5000
> pbl2-back | (node:16) UnhandledPromiseRejectionWarning: ReferenceError: UserSQL is not defined
> pbl2-back |     at getUserById (/app/src/route/userController.js:101:9)
> ```
> 
> Something wrong...

I had a type. I used Usersql instead of userSQL. The typo is now fixed

2020-12-22 04:38 UTC, ShimizuKazuki approved these changes
I checked

2020-12-22 04:45 UTC, kyamatek approved these changes

2020-12-22 05:22 UTC, merged