Show spots in user page
matsuoharuki/pbl2_group2 pull request #119
Opened 2021-01-13 06:17 UTC by tsukasa2

### Updated
- When you register a spot, DB also keeps your user ID.
- You can see spots which you registered in your user page.

### How to test
1. Log in the App.
1. Post some spots.
1. Jump to your user page, push hamburger button, and push "作成スポット". You can see the spots you registered.
### 【関連issue】
#97

2021-01-18 05:26 UTC, matsuoharuki commented on front/src/components/UserProfile/UserProfile.vue
>                      name: 'マクドナルド',
仮データとかパッと消せない？

2021-01-18 05:27 UTC, matsuoharuki commented on front/src/components/UserProfile/UserProfile.vue
> +            return getSpot('', '', '', user_id).then(result => {
getSpotの成功or失敗で例外処理を入れるとなおよい(今はいいけd)

2021-01-18 05:29 UTC, matsuoharuki commented on front/src/components/UserProfile/SpotListCard.vue
> +    left: 0,
各データの意味をdata内にコメントで書いて欲しい

2021-01-18 05:31 UTC, matsuoharuki commented on front/src/components/UserProfile/SpotListCard.vue
> +    getNumber: function(number){
各メソッドの大まかな機能を書いてもらえると助かります

2021-01-18 05:32 UTC, matsuoharuki approved these changes
動作は確認できました
コードないのメソッドやデータにはなるべくコメントをつけるようにしてください(ブーメランかも)

2021-01-18 05:41 UTC, kyamatek requested changes
レビュー終わりました
developブランチが更新されているから．マージしてコンフリクトの解消お願いします
余力があればSpotListCard.vueのインデントだけ2になっているので4に直しておいてもらえるとありがたい

2021-01-18 05:41 UTC, kyamatek commented on front/src/components/SpotRegister/SpotRegister.vue
> +        console.log( "$store: ", this.$store )
消しといてもいい？

2021-01-18 05:41 UTC, kyamatek commented on front/src/components/UserProfile/SpotListCard.vue
> +    left: 0,
leftとrightの意味を書いておいて欲しい
beginとendとかの方がいいのか？？

2021-01-18 06:18 UTC, tsukasa2 commented on front/src/components/UserProfile/UserProfile.vue
>                      name: 'マクドナルド',
いまは「おすすめスポット」に表示するスポットを選ぶ機能がないから，まだ仮データが必要そう．

2021-01-18 06:30 UTC, Asada0815 reviewed
レビュー終わりました．
ページ送りボタンが2種類あるんですけど，これはあってるんでしょうか．

2021-01-18 06:57 UTC, tsukasa2 commented
> レビュー終わりました．
> ページ送りボタンが2種類あるんですけど，これはあってるんでしょうか．

アプリの雰囲気とかに合わせて最終的にはどちらか消そうと思ってます．

2021-01-19 05:05 UTC, ShimizuKazuki approved these changes

2021-01-19 05:06 UTC, ShimizuKazuki reviewed
developをpullしてください

2021-01-19 05:26 UTC, ShimizuKazuki approved these changes

2021-01-19 05:26 UTC, kyamatek approved these changes

2021-01-19 05:30 UTC, merged