Feature/create university input form
matsuoharuki/pbl2_group2 pull request #120
Opened 2021-01-13 06:59 UTC by ShimizuKazuki

### Updated
- Add university information to user and spot.
- Change UI for registering university when sign up .
- Create spot file by university .

### How to test
1. Sign up with any university .
2. Post some spots.
3. You can filter spot by university when you push the bottom right button.

### 【関連issue】
#117

2021-01-13 07:33 UTC, Asada0815 approved these changes

2021-01-13 07:33 UTC, kyamatek requested changes

2021-01-13 07:33 UTC, kyamatek commented on front/src/components/Map/Map.vue
> +    <univ-button :univFlag="univFlag" v-on:click.native="updateUniv()"/>
非ログイン時に表示しないようにしときたい

2021-01-13 07:54 UTC, kyamatek commented
非ログイン時にピンが表示されないのは仕様ってことでいいかね

2021-01-13 08:55 UTC, matsuoharuki commented
未ログイン時にスポットが表示されないバグを修正

2021-01-18 04:35 UTC, kyamatek approved these changes

2021-01-18 04:41 UTC, merged