Feature/abatar setting
matsuoharuki/pbl2_group2 pull request #147
Opened 2021-04-21 06:53 UTC by Asada0815

### 【実装内容】
仮置きの画像データベースにフロント側からget/postする処理を実装
ユーザアイコンの設定をできるようにした

### 【テスト手順】
1. ユーザプロフィールページに遷移
2. 「アイコン画像を変更」をクリック
3. 画像を選択
4. 適当な大きさで画像を切り取り，設定する
5. ページ内のアイコンが変更されていることを確認
6. 更新したり，他のページから入り直してもアイコンが表示されることを確認
7. 開発フォルダに登録した画像が入ってることを確認 (`back/src/uploads`)
8. フォルダ内の画像を削除して，ユーザプロフィールのアイコンが初期化されることを確認

### 【関連issue】
#115

2021-04-21 08:55 UTC, matsuoharuki requested changes
ページ更新したら画像消えます
画像はローカルに保存されてるみたいです
もう一度確認をお願いします

2021-04-22 07:03 UTC, Asada0815 commented
バグ修正も兼ねて，#151がマージされた後に仕様変更したいと思います．

2021-04-28 06:17 UTC, Asada0815 commented
データベースに登録されている画像データフロントからget/postできるようにしました．

2021-04-28 06:44 UTC, matsuoharuki approved these changes
確認できました
いいと思います

2021-04-28 06:56 UTC, kyamatek commented
![スクリーンショット 2021-04-28 15 53 36](https://user-images.githubusercontent.com/49428851/116359775-2a871f00-a83a-11eb-889c-58c4ec68c86f.png)

「アイコン画像を変更」の真上にプロフィール画像がないのが違和感あるけど，自分の環境だけかな？

2021-04-28 07:10 UTC, ShimizuKazuki commented
<img width="407" alt="スクリーンショット 2021-04-28 16 08 32" src="https://user-images.githubusercontent.com/49428312/116361600-1c3a0280-a83c-11eb-9098-8008f40e70d9.png">
そんなにずれてない...?
ユーザプロファイルっていうタイトルとはずれてるけど

2021-04-28 07:23 UTC, ShimizuKazuki approved these changes
ずれは画面の大きさの問題だと思われる

2021-04-28 07:26 UTC, Asada0815 commented
うまいことアイコンとボタンを綺麗に揃えることができなくて，とりあえず放置してます．
ToDoBaby行きですね．

2021-04-28 07:26 UTC, kyamatek commented
ズレ問題は一旦保留でいいか

2021-04-28 07:28 UTC, kyamatek approved these changes

2021-04-28 07:31 UTC, merged