レビュー者の名前表示とリファクタリングとコメント追加
matsuoharuki/pbl2_group2 pull request #153
Opened 2021-04-22 06:15 UTC by takata6080

### 実装
- frontのコメント追加
- （ほかのユーザーページ作成の前段階として）レビューした人のユーザー名を表示
- ユーザーページ（/user）のUIを少し改善（スポット表示のページめくりボタンの改善）

### テスト
1.  ログインする．
2. マップ上のスポットをクリック
3. レビューを追加
4. リロード
5. 自分のレビューが追加され、そこに自分のユーザー名が表示されていることを確認
6. ユーザーページ（/user）でユーザー名変更後、その変更が反映されることを確認

### 関連issue
#85 , #145

2021-04-22 07:01 UTC, Asada0815 commented
動作確認しました．

- "Asada"のアカウントでレビュー投稿したのに，レビューの投稿者名が何故か"Takata"になってました
- レビュー投稿後や名前変更後にスポット詳細開いてもずっとお読み込み中のままでした（環境依存かもしれないので他の人の動作も確認したいです）

2021-04-22 07:05 UTC, Asada0815 commented
さっき改めて確認したら，自分の名前になってました
もしかしたらデータベースのラグが原因かもしれないですね

2021-04-22 07:12 UTC, Asada0815 commented
スポット詳細を開くたびにレビュー投稿者の名前が入れ替わってるみたいです

2021-04-22 07:33 UTC, matsuoharuki requested changes
・ユーザー名入れ替わり問題
・謎ロードできない問題

2021-04-22 07:34 UTC, Asada0815 commented on front/src/components/SpotDetail/SpotDetail.vue
> +                enumerated_reviews.push(Object.assign(raw_users[i],pert_of_reviews));
ここってどういう処理をやってる？
エラーメッセージでここが指定されてた

2021-04-22 07:34 UTC, Asada0815 commented on front/src/components/SpotDetail/SpotDetail.vue
> +                enumerated_reviews.push(Object.assign(raw_users[i],pert_of_reviews));
<img width="432" alt="スクリーンショット 2021-04-22 16 33 48" src="https://user-images.githubusercontent.com/49429196/115674454-9f64df80-a388-11eb-98ce-931c974f4ab3.png">

2021-04-22 08:09 UTC, takata6080 commented on front/src/components/SpotDetail/SpotDetail.vue
> +                enumerated_reviews.push(Object.assign(raw_users[i],pert_of_reviews));
ここはレビューリストとユーザーリストを合成して一つのオブジェクトにする処理を行っています。

2021-04-22 08:10 UTC, takata6080 commented
ユーザー名入れ替わり問題はおそらく解決しました（読み込み遅いけど）

2021-04-22 08:22 UTC, Asada0815 approved these changes
特に問題はないです！

2021-04-22 08:41 UTC, matsuoharuki requested changes
指摘していた問題は解決したのですが，ユーザー名を変更すると大学別検索がうまく動かなくなりました
確認お願いします

2021-04-28 05:56 UTC, takata6080 commented
@matsuoharuki 
確認しましたが、自分の環境だと問題無いように思います。

2021-04-28 06:17 UTC, matsuoharuki commented
> @matsuoharuki
> 確認しましたが、自分の環境だと問題無いように思います。

2021-04-28 06:20 UTC, matsuoharuki commented
確認したところ問題なかったです
コードをまだみてないので，そこを確認し次第approveします

2021-04-28 06:21 UTC, matsuoharuki commented on front/src/components/SpotDetail/SpotDetail.vue
> +            console.log('(change review page)change review page to ',number)
不要なログはなるべく消して欲しいです
テストをするときにログを打ち込んだりするので

2021-04-28 06:22 UTC, matsuoharuki commented on front/src/components/SpotDetail/SpotDetail.vue
> +        get_user_information: function() {//レヴューからユーザー名を取得する関数
関数名をキャメルケースで統一して欲しい

2021-04-28 06:28 UTC, matsuoharuki approved these changes
確認しました
細かいコメントを少ししたので，対応してマージしてください

2021-04-28 06:43 UTC, ShimizuKazuki approved these changes

2021-05-06 08:55 UTC, merged