Feature/edit spot
matsuoharuki/pbl2_group2 pull request #175
Opened 2021-05-13 08:52 UTC by Asada0815

### 【実装内容】
スポット情報を修正する画面を追加
スポット登録画面のコンポーネントを使い回すために一部リファクタリングをした
投稿時のレビューを変更するかどうかは未定のため，とりあえず非表示に

### 【テスト手順】
1. map画面に行く
2. 適当なスポットを開く
3. スポット名の右に「変更」ボタンがあるのでクリック
4. スポットを変更するUIに切り替わるので適当に入力
5. 下部の「変更」ボタンをクリックした後，ログを確認

### 【関連issue】
#171

2021-05-19 08:56 UTC, takata6080 commented
動作確認は完了しました。
これは修正者が作成者になる仕様になっていますか？
作成したスポットの作成者が自分ではなくなるとなんか嫌かもです。

2021-05-20 05:53 UTC, Asada0815 commented
> 動作確認は完了しました。
> これは修正者が作成者になる仕様になっていますか？
> 作成したスポットの作成者が自分ではなくなるとなんか嫌かもです。

確かに，作成者以外が自由に変更できるのは良く無いのですね...
仕様変更します．

2021-05-20 06:31 UTC, Asada0815 commented
自分が投稿したスポットのみ修正できるように変更しました．

2021-05-20 08:20 UTC, matsuoharuki requested changes
非ログイン状態だとスポット情報が見れません(延々とロード画面)
確認お願いします

2021-05-20 08:35 UTC, Asada0815 commented
> 非ログイン状態だとスポット情報が見れません(延々とロード画面)
> 確認お願いします

修正しました．

2021-05-26 07:19 UTC, tsukasa2 approved these changes

2021-05-26 08:36 UTC, Asada0815 reviewed
変更内容をバックエンドに伝えて，データベースの変更をできるようにしました
実際に変更されていることの確認もお願いします．

2021-05-27 06:09 UTC, matsuoharuki commented
スポットの登録時のデフォルト評価値が3になってて，評価に0をつけられなくなってますが，これは良いですかね？
個人的には評価0とかやばいのでこの仕様で問題ないとは思いますが...

2021-05-27 06:13 UTC, matsuoharuki requested changes
画像の変更処理がうまくいってないと思います
確認お願いします

2021-05-27 06:15 UTC, matsuoharuki commented
うまくいっていないでは抽象的でした
更新ボタンを押しても写真が更新されないということです

2021-05-27 06:17 UTC, Asada0815 commented
> スポットの登録時のデフォルト評価値が3になってて，評価に0をつけられなくなってますが，これは良いですかね？
> 個人的には評価0とかやばいのでこの仕様で問題ないとは思いますが...

スポット登録画面を流用する際に，デフォルト値を変更していました．
0評価をよしとするかは話し合いが必要かもしれませんが，すぐに変更できるのでとりあえずこのままでいいかのなと思っています．

> 画像の変更処理がうまくいってないと思います
> 確認お願いします
画像変更の処理を書くのをすっかり忘れていました...
後ほど実装するので再度レビューをお願いしたいです．

2021-05-27 06:54 UTC, matsuoharuki approved these changes
もろもろ大丈夫そうです

2021-05-27 07:36 UTC, takata6080 approved these changes
動作確認できました。大丈夫そうです。

2021-05-27 07:42 UTC, merged