スポットタイプを増やした
matsuoharuki/pbl2_group2 pull request #185
Opened 2021-05-27 06:44 UTC by matsuoharuki

## 【実装内容】
- スポットタイプを6種類に増やした
- それに伴って，スポットの評価項目を変更した
- さらに追加したスポット分のスポットアイコンを作成した(浅田くんが)

## 【テスト手順】
1. 新規スポットの登録で，選択肢に今までになかったスポット種別が表示されていることを確認する
2. 登録時に選択したタイプの表示が日本語になっていることを確認する
3. 既存のスポットタイプの評価基準が変わっていたり，新たに追加したスポットタイプの評価基準があることを確認する
4. 新たなスポットタイプで新たなスポットを登録する．
5. マップの検索ダイアログから，新たなスポットタイプを検索して，対応するアイコンのものだけが出ていることを確認する．

## 追加レビュー箇所
- 各評価の評価項目内容についてもいろいろとご意見いただきたいです(accomodetionのアメニティってのがわかりづらいなど)
- そのために割と多めにレビュアー設定してます

## 備考
- スポットの登録時にタイプを選ぶv-selectのフォームにも日本語の選択肢で表示したいのですが，ここで選択した内容がスポットのタイプとしてバインドされてうまくいきません。良い方法あったら教えてください。

## 【関連issue】
#183

2021-05-27 07:07 UTC, Asada0815 reviewed
> スポットの登録時にタイプを選ぶv-selectのフォームにも日本語の選択肢で表示したいのですが，ここで選択した内容がスポットのタイプとしてバインドされてうまくいきません。良い方法あったら教えてください。

https://qiita.com/bbapexx/items/299521d49df0869dc44f
このサイトのように，オブジェクトとしてvalueとtextをまとめて渡すとうまくいくかもしれません．

指標項目ですが，"アメニティ"よりは"快適さ"の方がわかりやすいのかなと個人的に思いました．あと，lifeworkの"価格"ってあんまイメージわかないような気がします．

2021-05-27 07:15 UTC, matsuoharuki commented
・「快適さ」っていうのも雰囲気あたりと似たような意味な気がするんですよね...
良い案募集します
・lifework 「価格」->「料金設定」にしました

2021-05-27 07:56 UTC, matsuoharuki commented
## 備考
- スポットの登録時にタイプを選ぶv-selectのフォームにも日本語の選択肢で表示したいのですが，ここで選択した内容がスポットのタイプとしてバインドされてうまくいきません。良い方法あったら教えてください。

-> 浅田くんのコメントをベースに修正しました
->あと，スポット登録の「スコア」の文字がv-chipになっていたのをただの<h>にしました

2021-06-02 08:11 UTC, kyamatek requested changes

2021-06-02 08:11 UTC, kyamatek commented on front/src/components/SpotDetail/SpotDetail.vue
> +            console.log("bbb")
削除お願いします

2021-06-02 08:11 UTC, kyamatek commented on front/src/components/SpotRegister/SpotInputForm.vue
> +                console.log(this.spot_data)
削除お願いします

2021-06-02 08:15 UTC, kyamatek approved these changes

2021-06-02 08:15 UTC, merged