other users profile UI のリファクタリング
matsuoharuki/pbl2_group2 pull request #186
Opened 2021-05-27 06:58 UTC by takata6080

### 【実装内容】
他のユーザーのプロフィールを見れるようにした。

### 【テスト手順】
1. map画面に行く
2. いずれかのスポットをクリック
3. レビュアーのアイコンが表示されていることを確認する．（レビュアーの写真がない場合はNo Image）
4. レビュアーの名前をクリック
5. レビュアーのプロフィール（小）が表示されることの確認
6. 「詳細を見る」ボタンをクリック
7. レビュアーのプロフィールページに飛ぶことを確認

### 問題点（TODO）
- /userページのスポットをクリックして同じ動作をしたらエラーが出ます。
- しかしながら、/userページのダイアログの詳細を見るを押した後、ページリロードをすると、ちゃんと動きます。
- これをどうにかしたい

### 【関連issue】
#128

2021-05-27 07:33 UTC, matsuoharuki commented
更新が反映されないのでレビュアー抜けます

2021-05-27 07:39 UTC, Asada0815 requested changes

2021-05-27 07:39 UTC, Asada0815 commented on front/src/components/share/UserProfileDialog.vue
> +            this.$router.push({ path: 'user', query: { otherUser: true } })
おそらく，userページにいながらuserページに飛んでいるためエラーが起きていると思います．
現在いるページで場合分けするか，スポット詳細開くときはmap画面に遷移するなどの対処がいると思います．
https://www.softel.co.jp/blogs/tech/archives/6628

2021-05-27 08:31 UTC, takata6080 commented on front/src/components/share/UserProfileDialog.vue
> +            this.$router.push({ path: 'user', query: { otherUser: true } })
強制リロード処理を追加して一応解決したと思います。

2021-06-02 07:37 UTC, takata6080 commented
問題点解消しました。再度確認お願いします。

2021-06-02 07:43 UTC, Asada0815 approved these changes

2021-06-02 08:08 UTC, kyamatek approved these changes

2021-06-02 08:09 UTC, merged