Delete User
matsuoharuki/pbl2_group2 pull request #196
Opened 2021-06-03 07:36 UTC by ShimizuKazuki

#132 
Add Function to delete user.

[Test]

1. click the delete button, then you can see password form.
2. (sub)when you send wrong password, you move to a different form which can enter password again.
3. when you enter correct password, move a form to confirm deleting.
4. when you click "yes", account can't be used and logout.
5. when you click "no",  dialog will be closed.

Additionally, I changed some part of backend to get only spots, not reviews. 
Due to this change, I got so many conflict, so I want you to check other part work correctly.

2021-06-03 07:59 UTC, Asada0815 requested changes
ユーザの削除はうまく機能しているのですが，削除していないユーザでのログインができなくなっています．

2021-06-03 08:16 UTC, ShimizuKazuki commented
返すの忘れてました

2021-06-03 08:25 UTC, Asada0815 approved these changes

2021-06-09 06:21 UTC, matsuoharuki approved these changes
動作は問題ないと思います
削除したユーザーが作ったスポットやレビューはどうするべきか考えた方がいいかもです

2021-06-09 06:24 UTC, merged