UserEdit.vue bug fix
matsuoharuki/pbl2_group2 pull request #199
Opened 2021-06-09 06:01 UTC by takata6080

### 実装
- ユーザーページでユーザー情報を修正すると大学名が表示されなくなるバグ修正

### テスト
1. ログインする
2. ユーザーページに行く
3. ユーザー情報を修正する
4. 大学名が消えないことを確認する

### 関連issue
#191

2021-06-09 06:19 UTC, ShimizuKazuki commented on front/src/components/Login/Login.vue
> +                    // console.log(res)
デバッグ用の標準出力ならコメントアウトじゃなくて消しちゃってください。

2021-06-09 06:19 UTC, ShimizuKazuki commented on front/src/components/UserProfile/UserProfile.vue
> +        // console.log('user information ',this.user)
デバッグ用の標準出力ならコメントアウトじゃなくて消しちゃってください。

2021-06-10 06:29 UTC, Asada0815 reviewed
大学名はちゃんと表示されました．
要らなくなったデバッグログを消したらマージしてもいいと思います．

2021-06-10 07:48 UTC, ShimizuKazuki requested changes

2021-06-10 07:48 UTC, ShimizuKazuki commented on front/src/components/UserProfile/UserProfileDetail.vue
> +
すでに同じメソッドがdevelopにあるから重複してエラー出てる。
消してだいじょうぶ。

2021-06-16 07:25 UTC, takata6080 commented on front/src/components/UserProfile/UserProfileDetail.vue
> +
修正完了しました。

2021-06-17 06:26 UTC, kyamatek approved these changes
問題ないと思います

2021-06-17 06:35 UTC, ShimizuKazuki approved these changes
OKでした

2021-06-17 06:36 UTC, merged