おすすめスポット2
matsuoharuki/pbl2_group2 pull request #210
Opened 2021-06-16 07:29 UTC by tsukasa2

### 実装
- ユーザーページのおすすめスポットのところに，おすすめスポットを表示できるようになりました．
    - 自分と同じ大学の人に投稿されたスポットのうち，複数人によってレビューされたものを評価の高い順に6件表示しています．
- 作成スポットとレビューしたスポットも評価の高い順にソートして表示できるようになりました．

### テスト
1. ログインする
2. ユーザーページにおすすめスポットが確認されることを確認
3. 各種スポットが評価の高い順に表示されることを確認

### 関連issue
#145

### メモ
- 別ファイルにmethodをまとめておく方が設計としてはきれいだと思うので時間があればリファクタリングしたい
- スポットの多いアカウントだとロードに時間がかかるけど，清水くんの作業が終われば改善される？

2021-06-16 08:20 UTC, kyamatek requested changes
コンソールで`success getRecommendedSpots UserProfile.vue?ebc3:256`
は出るんだけど，そのあとが進まない

2021-06-16 08:20 UTC, kyamatek commented on front/src/components/UserProfile/UserProfile.vue
> +            if(this.show_count==3) {
else使って書いてもいいのでは？

2021-06-16 08:20 UTC, kyamatek commented on front/src/components/UserProfile/UserProfile.vue
> +                // var added = 0;
消してもいいコメントっぽい？

2021-06-16 08:30 UTC, tsukasa2 commented
@kyamatek 
> コンソールで`success getRecommendedSpots UserProfile.vue?ebc3:256`
> は出るんだけど，そのあとが進まない

success getRecommendedSpots以外に，success getSpotByUserIdとsuccess getSpotYouReviewedも表示されてるか確認できる？

2021-06-16 08:59 UTC, kyamatek commented
> success getSpotByUserIdとsuccess getSpotYouReviewed

success getSpotByUserIdは出てるけど，success getSpotYouReviewedは出てないっぽいね

2021-06-17 06:03 UTC, takata6080 commented
自分のアカウントのユーザーページは開けますが山手君のユーザーページが開けない

2021-06-17 06:12 UTC, matsuoharuki commented
今回の機能そのものとは関係ないのですが，GetProfileInformation.jsのgetReviewBySpotIdとかgetReviewByUserIdの出力をバグ修正の関係で変更したので，developをマージするといろいろ起こるかもです
もし，コンフリクトだのバグだのが発生したら，変更点伝えるのでご連絡ください

2021-06-17 06:31 UTC, Asada0815 commented
スポットを一個も作っていないアカウントだとユーザページが表示されないっぽいです
おすすめ機能は大丈夫そうです

2021-06-17 06:32 UTC, tsukasa2 commented
例外処理に漏れがあったみたいです．福岡大学のyamateさんのページが開たのでたぶん大丈夫かなと思います

2021-06-17 07:08 UTC, kyamatek reviewed
おすすめスポットはちゃんと表示されました．
ページをリロードした直後にこんな感じになることがある（[1]とか押したらちゃんとスポットが表示される）のですぐ直せそうだったら対応お願いします．
めんどそうだったら後回しでも問題ないと思う
<img width="919" alt="スクリーンショット 2021-06-17 16 02 33" src="https://user-images.githubusercontent.com/49428851/122348017-a6256280-cf85-11eb-8551-ddcad5c400c0.png">

2021-06-17 07:08 UTC, kyamatek approved these changes

2021-06-17 07:20 UTC, Asada0815 approved these changes

2021-06-17 07:22 UTC, merged