To do baby user spotdetail
matsuoharuki/pbl2_group2 pull request #213
Opened 2021-06-16 08:28 UTC by matsuoharuki

ユーザーページからスポット詳細を見れないバグを修正

[test]
- ユーザーページにいく
- 作成スポットから任意のスポットをクリック
- スポット詳細を開けるかテスト

[備考]
- いくつかのスポットがspotdetailを開くと，ワーニングだらけになる(今のとこ動作は正常なので放置してる)

2021-06-16 08:38 UTC, matsuoharuki commented
### 備考の事象について
ここでエラーが出てるものは，レビュー追加の画面が壊れてました．
よって要修正事項ですね...

2021-06-16 08:55 UTC, matsuoharuki commented
### スポット投稿画面の表示バグ

こちらもついでに修正しました
確認お願いします

[test]
- スポット詳細を開く
- レビュー投稿画面を開いて表示が正しいかを確認する
いくつかのつポットで見てもらえると助かります

2021-06-16 08:56 UTC, Asada0815 commented
バグは直ってたので問題ないです！

例のエラーですが，
<img width="539" alt="スクリーンショット 2021-06-16 17 53 01" src="https://user-images.githubusercontent.com/49429196/122189351-d4df0280-cecb-11eb-80d6-08750f069f32.png">
レビュー投稿コンポーネント(SpotReviewRegister.vue)の初期化時に，タイプとタグがコンマで分割されていないままindexに渡してしまってるからっぽいです

ついでに直してもらえると助かります

2021-06-16 08:56 UTC, Asada0815 requested changes
バグは直ってたので問題ないです！

例のエラーですが，
<img width="539" alt="スクリーンショット 2021-06-16 17 53 01" src="https://user-images.githubusercontent.com/49429196/122189351-d4df0280-cecb-11eb-80d6-08750f069f32.png">
レビュー投稿コンポーネント(SpotReviewRegister.vue)の初期化時に，タイプとタグがコンマで分割されていないままindexに渡してしまってるのが原因っぽいです
レビュー投稿時のグラフ表示がもそれでバグってるようです

ついでに直してもらえると助かります

2021-06-16 08:58 UTC, matsuoharuki commented
> バグは直ってたので問題ないです！
> 
> 例のエラーですが，
> <img alt="スクリーンショット 2021-06-16 17 53 01" width="539" src="https://user-images.githubusercontent.com/49429196/122189351-d4df0280-cecb-11eb-80d6-08750f069f32.png">
> レビュー投稿コンポーネント(SpotReviewRegister.vue)の初期化時に，タイプとタグがコンマで分割されていないままindexに渡してしまってるのが原因っぽいです
> 
> ついでに直してもらえると助かります

これも多分直したので，再度ブランチをpullして確認してみて欲しい...

2021-06-16 09:01 UTC, Asada0815 approved these changes

2021-06-17 06:33 UTC, takata6080 commented
動作確認しました。特に問題なかったです。

2021-06-17 06:38 UTC, kyamatek requested changes
動作は問題なさそうですが，developとコンフリクトしてるので修正お願いします．

2021-06-17 07:41 UTC, takata6080 commented
GetProfileInformation.jsとUserProfile.vueの統合の影響で少しめんどくさいかもしれません。

2021-06-17 08:21 UTC, matsuoharuki commented
コンフリクト治らないので，再実装してまたプルリク作ります

2021-06-17 08:21 UTC, closed without merging