[Fix] Reduce image request in user profile and spot detail
matsuoharuki/pbl2_group2 pull request #231
Opened 2021-06-24 07:42 UTC by ShimizuKazuki

ユーザプロファイルでオススメスポットなどを取ってくる処理を軽くするため、表示件数分だけリクエストを送るように変更。
同じくスポット詳細でレビューしたユーザを取ってくる処理を軽くした。

[Test]
スポット詳細画面でレビューしたユーザが表示される。
ページを送ると別のユーザが表示される。

ユーザプロファイルからオススメスポットが表示される。
ページ送り、別のページ（作成したスポット）も表示される。

2021-06-24 07:53 UTC, tsukasa2 commented
おすすめスポットに表示されているスポットの詳細に飛べないんだけど，別のブランチで誰かが修正してくれてたっけ？

2021-06-24 07:59 UTC, tsukasa2 commented
> おすすめスポットに表示されているスポットの詳細に飛べないんだけど，別のブランチで誰かが修正してくれてたっけ？
> このブランチではこれで問題ないんかな

git pullし直したら解決しました．
問題ないと思います！

2021-06-24 07:59 UTC, tsukasa2 approved these changes

2021-06-24 08:01 UTC, takata6080 commented
新規ユーザー（スポット作成情報がないorその大学でスポット作成者がいない）の場合ずっとロード画面になります。

2021-06-24 08:07 UTC, Asada0815 requested changes
ユーザ名とアイコンの対応がバラバラになってます
おそらく名前の方が間違って入れられてる？
<img width="600" alt="スクリーンショット 2021-06-24 17 07 20" src="https://user-images.githubusercontent.com/49429196/123226693-da150080-d50e-11eb-805d-8d0e48a4f7cf.png">

2021-06-24 08:14 UTC, tsukasa2 commented
僕の方でも試してみたけど，スポットの評価を開くたびにアイコンと名前の対応が変わってるっぽい？

2021-06-24 08:34 UTC, ShimizuKazuki commented
修正完了。
フロントエンドは連想配列使わないとバグるなやっぱり

2021-06-24 08:41 UTC, Asada0815 approved these changes
OKです！

2021-06-24 08:43 UTC, tsukasa2 commented
OKです！

2021-06-24 08:50 UTC, takata6080 approved these changes
動作確認完了しました。OKです

2021-06-24 09:02 UTC, takata6080 requested changes
develop のUserEdit.vueの変更が反映されてないっぽくて、editダイアログがうまく出ません。UserProfileDetail.vueの内容をUserProfile.vueにコピペすればなおるかなと思います。

2021-06-30 06:45 UTC, takata6080 approved these changes
問題なさそうです。

2021-06-30 06:52 UTC, merged