#24 Feature/saveReview
matsuoharuki/pbl2_group2 pull request #49
Opened 2020-11-09 04:43 UTC by ShimizuKazuki

Description: 
- Added a function saving review data to the database
To test this pull request:
- In the docker, run this command
```
node src/database/ReviewSQL.js
```
- You can see the sample data in the code like this . Review_id should be unique, so please do not use same id.
```
 testReview = new Review("review_id111", "spot_id1111", 'comment2', 90, "user_id111");
```
- when you run the command, you can see your sample data in the database.
Success condition:
```
2020-11-????:???????? [ReviewSQL] debug: saved review: [object Object]
```

2020-11-09 08:41 UTC, tsukasa2 approved these changes

2020-11-10 04:26 UTC, ShimizuKazuki reviewed
Add Review Route

2020-11-10 04:56 UTC, kyamatek requested changes

2020-11-10 04:56 UTC, kyamatek commented on back/src/database/ReviewSQL.js
> +module.exports.saveReview = function(newReview){
async function にした方がいいんじゃない？

2020-11-10 04:56 UTC, kyamatek commented on back/src/database/ReviewSQL.js
> +module.exports.getReviewBySpotId = function(spotId){
ここもasync

2020-11-10 05:00 UTC, kyamatek approved these changes

2020-11-17 05:15 UTC, ONourry requested changes
Change Function names, add check to make sure we have all the data for the reviews. Remove unused or commented out code

2020-11-17 05:15 UTC, ONourry commented on back/src/route/reviewController.js
> +    async register(req, res){
Can you change name to saveReview

2020-11-17 05:15 UTC, ONourry commented on back/src/route/reviewController.js
> +        let salt = bcrypt.genSaltSync(10);
Why do we need a salt for encryption?

2020-11-17 05:15 UTC, ONourry commented on back/src/route/reviewRoute.js
> +router.post("/register",reviewController.register);
Change to saveReview

2020-11-17 05:15 UTC, ONourry commented on back/src/route/spotController.js
> +    async register(req, res){
Change to saveSpot

2020-11-17 05:15 UTC, ONourry commented on back/src/route/spotController.js
> +    async search(req, res){
change to getSpot to make it more clear

2020-11-17 05:15 UTC, ONourry commented on back/src/route/spotRoute.js
> +router.post("/register",spotController.register);
Change to saveSpot

2020-11-17 05:15 UTC, ONourry commented on back/src/server.js
>  //app.use('/spot',spotRoute)
Why is this commented out? Don't we need it?

2020-11-17 05:15 UTC, ONourry commented on back/src/route/spotController.js
> +        // return res.status(200).json({"success": true, "spotId": spot['spotId'], "spotName": spot['spotName']});
Remove code if not used

2020-11-17 05:15 UTC, ONourry commented on back/src/database/ReviewSQL.js
> +// const testReview = new Review("review_id114", "spot_id1111", 'comment2', 90, "user_id111");
Remove code if not used

2020-11-17 05:15 UTC, ONourry commented on back/src/route/spotController.js
> +const bcrypt = require('bcryptjs');
I don't think we need encryption here

2020-11-17 05:15 UTC, ONourry commented on back/src/route/reviewController.js
> +        const review = new Review(uuidv4(), spotId, comment, score, userId);
We need to make sure that the data exists before creating the Review. Right now the system allows us to create review with no spotId or comment.

<img width="452" alt="Screen Shot 2020-11-17 at 2 12 47 PM" src="https://user-images.githubusercontent.com/11179982/99349365-2e079900-28df-11eb-922e-4f0d6fee12bc.png">

2020-11-17 05:16 UTC, ONourry commented on back/src/route/reviewController.js
> +        const review = new Review(uuidv4(), spotId, comment, score, userId);
Request used: 
{
    "spotId" : "",
    "comment" : "", 
    "score" : 100, 
    "userId" : "TestingEmptyFields"
}

2020-11-17 07:19 UTC, ShimizuKazuki reviewed
I added checkQuery to check spot is exist

2020-11-17 07:20 UTC, ONourry commented on back/src/database/ReviewSQL.js
> +            debug(fileLabel,"saved review: " + newReview);
a review is an object, you need to use util.inspect to view it when we when to log in terminal. Otherwise it will only show [Object object]

2020-11-18 05:51 UTC, closed without merging

2020-11-18 05:51 UTC, ShimizuKazuki commented
merge to spot branch