Feature/9 user edit information
matsuoharuki/pbl2_group2 pull request #55
Opened 2020-11-10 06:04 UTC by takata6080

### 【実装内容】
ユーザープロフィール編集UI作成
  
### 【テスト手順】
1. ユーザープロフィール画面に移動 (/user)
1. 「EDIT」ボタンを押す
1. 修正用のUIが表示されるのを確認
1. 「変更しない」を押すとその項目が消える
1. 「CLEAR」をおすともとに戻る
1. 修正項目を入力
1. 修正ボタンを押す
1. consoleに修正後の"ユーザー名","メールアドレス","パスワード"の3つが表示されることを確認（変更しなかったデータ元のデータが表示される）
1. １～５を繰り返す（注意：2回目以降は一回「CLEAR」ボタンを押さないといけない仕様になっているため後に修正します）

### 【関連issue】
#9

2020-11-10 06:29 UTC, matsuoharuki commented on front/src/components/UserEdit.vue
> +                <v-text-field label="変更後のパスワード"
設定するパスワードの脆弱性を制限できないか
簡単なのは8文字以上をリジェクト
信頼性高いのはメアドと同じような正規表現解析により評価する(どこかしらに転がってそう)

2020-11-10 06:31 UTC, matsuoharuki commented on front/src/components/UserEdit.vue
> +    <v-card
最初にダイアログを開いた時に全部空白だから全部にエラーダイアログが出るのがなんか嫌
修正ボタンを押した時に判定してダイアログを出したらどうでしょう？

2020-11-10 06:34 UTC, matsuoharuki commented on front/src/components/UserEdit.vue
> +                    <v-btn @click="NotChange(1)">変更しない</v-btn>
変更しないボタンはいまいちだと思う
1.ユーザー名変更ダイアログ
2.メールアドレスを変更するダイアログ(この時はパスワードの確認もいれたい)
3.パスワードを変更するダイアログ
の3つを独立して使いたいかなー

2020-11-10 06:35 UTC, matsuoharuki commented on front/src/components/UserProfile.vue
> +                            edit
editのiconをvuetifyから持ってきて使うとお洒落かも

2020-11-10 06:37 UTC, matsuoharuki requested changes
コメントをもっと書いてほしいです
後、正直ちょっと使いづらく感じるのでもう少し改善してもらいたい...

2020-11-10 06:52 UTC, Asada0815 commented on front/src/components/UserEdit.vue
> +            editer: true,
isDisplayedWindowみたいに変数名だけでわかるような名前がいいと思います

2020-11-10 06:53 UTC, Asada0815 commented on front/src/components/UserEdit.vue
> +            showPassword2 : false,
before, afterをつけておくと分かりやすい

2020-11-10 07:40 UTC, Asada0815 commented on front/src/components/UserEdit.vue
> +                    <v-btn @click="NotChange(1)">変更しない</v-btn>
松尾くんの意見、僕も賛成です
これ使ってみてはどうでしょうか
https://vuetifyjs.com/en/components/steppers/

2020-11-10 07:42 UTC, Asada0815 commented on front/src/components/UserEdit.vue
> +            editpassword: true,
editPassword

2020-11-10 07:42 UTC, Asada0815 commented on front/src/components/UserEdit.vue
> +            emailRules2: [
同じくbefore,afterの方がいい

2020-11-10 07:43 UTC, Asada0815 commented on front/src/components/UserEdit.vue
> +            passwordRules2: [
ここも

2020-11-10 07:46 UTC, Asada0815 commented on front/src/components/UserEdit.vue
> +        initialState: function() {
メソッド名：1単語目が動詞    
変数名：1単語目が名詞  
のように決めておくと分かりやすいかも  
  
この場合だと、initalizeState とか

2020-11-10 07:48 UTC, Asada0815 commented on front/src/components/UserEdit.vue
> +        NotChange: function(value){
メソッド名がちょっと分かりにくい
入力フォームを非表示にしているので、hideInputForm とかはどうでしょう

2020-11-10 07:50 UTC, Asada0815 commented on front/src/components/UserEdit.vue
> +        NotChange: function(value){
できればvaluemも分かりやすくしておきたい  
例えばstring型を受け取るようにするといいかも

2020-11-10 07:56 UTC, Asada0815 commented on front/src/components/UserProfile.vue
> +                        ユーザー名
インデント一つ深くなってます

2020-11-10 08:00 UTC, Asada0815 commented on front/src/components/UserProfile.vue
> +    <v-container fluid class="px-20">
ここも同じくv-containerが必要ないかも

2020-11-10 08:00 UTC, Asada0815 commented on front/src/components/UserProfile.vue
> +        <v-container width=50 class="px-16">
v-containerを入れ子にしなくてもいいかもしれない

2020-11-10 08:02 UTC, Asada0815 commented on front/src/components/UserProfile.vue
> +        FromUserEdit: function(value){
将来的に消すかもしれないですが、メソッド名に動詞を入れておいた方がいいです
recieveEditedProfile など

2020-11-10 08:05 UTC, Asada0815 approved these changes
レビュー終わりました。

2020-11-18 06:07 UTC, merged

2020-11-30 08:59 UTC, matsuoharuki commented
Userのemailアドレスだけを変更するときにパスワード確認はさすがにあったほうがよさそう
今のままだとパスワードを知らなくてもuserのメールアドレスを変更できる