get spot by ranges of x and y
matsuoharuki/pbl2_group2 pull request #69
Opened 2020-11-30 06:47 UTC by tsukasa2

I added "xMax", "xMin", "yMax" and "yMin" to keyword to search spots.
To test it on Postman,
- Request URL: GET http://localhost:5000/spot/getSpot
- Body: JSON, for example,
```
{
    "spotType": "shopping",
    "xMax": 180,
    "xMin": -180,
    "yMax": 34,
    "yMin": 0
}
```

2020-11-30 07:55 UTC, ShimizuKazuki requested changes
{
    "spotType": "shopping",
    "xMin": 50,
    "xMax": 40
}
=>
{
    "success": false,
    "error": "spot does not exist"
}

x, yの範囲に条件つけたほうがいいかも

2020-12-01 04:13 UTC, tsukasa2 commented
常に-180 <= xMin <= xMax <= 180かつ-90 <= yMin <= yMax <= 90となるように修正しました．

2020-12-01 04:22 UTC, ShimizuKazuki requested changes

2020-12-01 04:22 UTC, ShimizuKazuki commented on back/src/database/makeSQL.js
> +            console.log("xMin is bigger than xMax.");
ログはただの標準出力より
error(fileLabel,"Error while saving spot: " + err);
こんな感じにしたほうがいい

2020-12-01 04:22 UTC, ShimizuKazuki commented on back/src/database/makeSQL.js
> +            console.log("yMin is bigger than yMax.");
here too

2020-12-01 04:26 UTC, ONourry commented
This request should use the new empty function from #62. We should merge the other PR first

2020-12-07 07:06 UTC, tsukasa2 commented
isEmpty( X ) returns true if X is 0. However, xMax, xMin, yMax and yMin can be 0 in this case, I think.

2020-12-07 07:10 UTC, ONourry commented
It would be more efficient to modify isEmpty() and allow value 0 than adding extra || value == 0 everywhere.

2020-12-07 07:40 UTC, tsukasa2 commented
I modified isEmpty( X ) to return FALSE when X is 0.
( The commit massage is wrong ... 🤦  )

2020-12-07 07:43 UTC, ShimizuKazuki approved these changes

2020-12-07 07:44 UTC, merged